/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19-11.7.2-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: sih_db
-- ------------------------------------------------------
-- Server version	12.3.3-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;

--
-- Table structure for table `food`
--

DROP TABLE IF EXISTS `food`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `food` (
  `rule_id` varchar(255) NOT NULL,
  `additives` varchar(255) DEFAULT NULL,
  `brand_name` varchar(255) DEFAULT NULL,
  `calcium_mg` double DEFAULT NULL,
  `calories_kcal` double DEFAULT NULL,
  `carbohydratesg` double DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `cholesterol_mg` double DEFAULT NULL,
  `dietary_fiberg` double DEFAULT NULL,
  `expire_data` varchar(255) DEFAULT NULL,
  `ingredients` longtext DEFAULT NULL,
  `iron_mg` double DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `preservatives` varchar(255) DEFAULT NULL,
  `proteinsg` double DEFAULT NULL,
  `saturated_fatg` double DEFAULT NULL,
  `serving_sizeg` double DEFAULT NULL,
  `sodium_mg` double DEFAULT NULL,
  `sub_category` varchar(255) DEFAULT NULL,
  `sugarg` double DEFAULT NULL,
  `total_fatg` double DEFAULT NULL,
  `trans_fatg` double DEFAULT NULL,
  `vitamin` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `food`
--

LOCK TABLES `food` WRITE;
/*!40000 ALTER TABLE `food` DISABLE KEYS */;
INSERT INTO `food` VALUES
('BC1','INS 442, INS 476, Added Flavours','Cadbury',0,70.1,8,'Solid items',2.7,0.4,'12','Sugar, Milk Solids (22-23%), Cocoa Butter, Cocoa Solids, Edible Vegetable Fat, Emulsifiers (INS 442, INS 476), Added Flavours (Natural, Nature Identical and Artificial - Ethyl Vanillin)',0,'Cadbury Dairy Milk Chocolate','None specifically listed',1,2.6,13.2,17,'Chocolate',7.5,3.8,0.01,'0.0'),
('BE1','Sucralose, Acesulfame K, Citric Acid, Sodium Citrate','Monster Energy',0,9,4.4,'Beverages',0,0,NULL,'Carbonated Water, Citric Acid, Taurine, Sodium Citrate, Flavourings, Panax Ginseng Root Extract, Sucralose, Acesulfame K, Caffeine, Sorbic Acid, Benzoic Acid, L-Carnitine L-Tartrate, Vitamins B3, B5, B6, B12, Sodium Chloride, D-Glucuronolactone, Guarana Seed Extract, Inositol',0,'Monster Ultra Zero Sugar','Sorbic Acid, Benzoic Acid',NULL,0,500,400,'Energy Drink',0,0,0,'B3, B5, B6, B12'),
('BE10','Sucralose, Citric Acid, Sodium Citrates, Potassium Citrates, L-Carnitine, Inositol, Maltodextrin, Colour E150c','Monster Energy',0,185,46,'Beverages',0,0,'24','Carbonated Water, Sugar, Fruit Juices From Concentrate (Apple, Guava, Passion Fruit, Pineapple, Orange, Lemon), Glucose Syrup, Flavourings, Carbon Dioxide, Taurine (0.4%), Citric Acid, Potassium Citrates, Sodium Citrates, Panax Ginseng Root Extract, Potassium Sorbate, Caffeine (0.03%), Ascorbic Acid, Vitamins B2, B3, B6, B12, Sucralose, L-Carnitine L-Tartrate, Sodium Chloride, Colour E150c, D-Glucuronolactone, Guarana Seed Extract, Inositol, Maltodextrin',0,'Monster Juiced Ripper','Potassium Sorbate',0,0,500,76,'Energy Drink',42,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BE11','Calcium Lactate, Sodium Citrates, Citric Acid, Ascorbic Acid, Sucralose','Monster Energy',NULL,219,55,'Beverages',0,0,'24','Carbonated Water, Sucrose, Fruit Juices from Concentrate (4%) (Orange, Lemon), Glucose Syrup, Lemon Fruit, Natural Flavourings, Taurine (0.4%), Acidity Regulators (Calcium Lactate, Sodium Citrates), Citric Acid, Panax Ginseng Root Extract (0.08%), Preservative (Potassium Sorbate), Ascorbic Acid, Caffeine (0.03%), Vitamins (B3, B6, B2, B12), L-Carnitine L-Tartrate (0.004%), Sweetener (Sucralose), Sodium Chloride, D-Glucuronolactone, Guarana Seed Extract (0.002%), Inositol, Maltodextrin',NULL,'The Doctor VR46 Energy Drink','Potassium Sorbate',0,0,500,32,'Energy Drink',52,0,0,NULL),
('BE12','Sucralose, Sunset Yellow FCF, Brilliant Blue FCF','Predator',NULL,73,18,'Beverages',0,0,'24','Carbonated Water, Sucrose, Acidity Regulators (Citric Acid, Sodium Citrate, Tartaric Acid), Artificial Mixed Fruit Flavour, Taurine (100mg/100ml), Preservatives (Potassium Sorbate, Sodium Benzoate), Caffeine (30mg/100ml), Sweetener (Sucralose), Vitamins (B3, B6), Synthetic Food Colours (Sunset Yellow FCF, Brilliant Blue FCF), Inositol (1mg/100ml)',NULL,'Gold Strike Energy Drink','Potassium Sorbate, Sodium Benzoate',0,0,300,123,'Energy Drink',16,0,0,NULL),
('BE13','Taurine, Caffeine, Niacin, Vitamin B2, Vitamin B6, Vitamin B12, Caramel Colour','Red Bull',NULL,112.5,27.5,'Beverages',0,0,NULL,'Water, Sucrose, Glucose, Citric Acid, Carbon Dioxide, Taurine, Acidity Regulators, Flavours, Colour (Caramel), Caffeine, B-Group Vitamins (Niacin, Vitamin B2, Vitamin B6, Vitamin B12)',NULL,'Red Bull Energy Drink','24',0,0,250,102.5,'Energy Drink',27.5,0,0,NULL),
('BE14','Sucralose, Acesulfame K, Taurine, Caffeine, B-Group Vitamins','Red Bull',NULL,7.5,0,'Beverages',0,0,NULL,'Water, Acidulants, Carbon Dioxide, Taurine, Acidity Regulators, Caffeine, B-Group Vitamins (Niacin, Vitamin B2, Vitamin B6, Vitamin B12), Flavours, Sucralose, Acesulfame K',NULL,'Red Bull Sugarfree Energy Drink','24',0,0,250,105,'Sugar Free Energy Drink',0,0,0,NULL),
('BE15','Taurine, Caffeine, Niacin, Vitamin B2, Vitamin B6, Vitamin B12','Red Bull',NULL,112.5,27.5,'Beverages',0,0,NULL,'Water, Sucrose, Glucose, Acidulants, Carbon Dioxide, Taurine, Acidity Regulators, Caffeine, B-Group Vitamins, Flavours, Colour',NULL,'Red Bull Pink Edition White Peach Energy Drink','24',0,0,250,87.5,'Energy Drink',27.5,0,0,NULL),
('BE16','Citric Acid, Sodium Citrates, Sucralose, Acesulfame K, Ammonia Caramel, Caffeine, Glucuronolactone, Inositol, Vitamins B2, B3, B5, B6, B12','HELL Energy',NULL,5,0,'Beverages',0,0,NULL,'Water, Citric Acid, Carbon Dioxide, Sodium Citrates, Flavourings, Caffeine, Ammonia Caramel, Sucralose, Acesulfame K, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B2, Vitamin B12, Glucuronolactone, Inositol',NULL,'HELL Classic Zero Sugar Energy Drink','24',0,0,250,NULL,'Sugar Free Energy Drink',0,0,0,NULL),
('BE17','Citric Acid, Sodium Citrates, Sucralose, Acesulfame K, Ammonia Caramel, Caffeine, Glucuronolactone, Inositol, Vitamins B2, B3, B5, B6, B12','HELL Energy',NULL,115,27.5,'Beverages',0,0,NULL,'Water, Sugar, Citric Acid, Carbon Dioxide, Black Carrot Concentrate, Sodium Citrates, Flavourings, Caffeine, Ammonia Caramel, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B2, Vitamin B12, Sucralose, Acesulfame K, Glucuronolactone, Inositol',NULL,'HELL Black Cherry Energy Drink','24',0,0,250,NULL,'Energy Drink',27.5,0,0,NULL),
('BE18','INS 329, INS 508, INS 330, INS 296, INS 331, INS 202, Nature Identical Peach & Passion Flavour, Vitamins B3, B5, B7','O\'cean',NULL,105,25,'Beverages',0,0,'24','Water, Reconstituted Peach Juice from Concentrate, Sugar, Glucose, Minerals (INS 329, INS 508), Acidity Regulators (INS 330, INS 296, INS 331), Nature Identical Flavouring Substances (Peach & Passion), Permitted Class II Preservative (INS 202), Vitamins B3, B5, B7',NULL,'Peach & Passion Fruit Drink','Potassium Sorbate (INS 202)',1.3,0,250,12.5,'Fruit Drink',25,0,0,NULL),
('BE19','Taurine, Caffeine, Inositol, Choline, Lysine, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B12, Citric Acid, Colouring, Flavouring','Red Bull',NULL,180,45,'Beverages',0,0,NULL,'Water, Sucrose, Citric Acid, Taurine, Choline, Inositol, Lysine, Caffeine, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B12, Flavouring, Colouring',NULL,'Kratingdaeng Red Bull Energy Drink','24',1,0,250,260,'Energy Drink',39,0,0,NULL),
('BE2','Sucralose, Citric Acid, Sodium Citrate','Monster Energy',0,167,42,'Beverages',0,0,'24','Carbonated Water, Sucrose, Glucose Syrup, Citric Acid, Sodium Citrate, Taurine, Panax Ginseng Extract, L-Carnitine, Caffeine, Sorbic Acid, Benzoic Acid, Sucralose, Vitamins B3, B6, B12, D-Glucuronolactone, Inositol, Guarana Extract',0,'Monster Energy Original Green','Sorbic Acid, Benzoic Acid',0,0,350,280,'Energy Drink',33,0,0,'B3, B6, B12'),
('BE20','Taurine, D-Glucuronolactone, Caffeine, Inositol, Lysine, Choline Bitartrate, Maltitol Syrup, Acesulfame Potassium, Sucralose, Tartrazine, Ponceau 4R, Vitamins B3, B5, B6, B12','Red Bull',NULL,71,16.8,'Beverages',0,0,'24','Maltitol Syrup, Sucrose, Citric Acid, Sodium Bicarbonate, Taurine, Mixed Fruit Flavour, D-Glucuronolactone, Sodium Benzoate, Acesulfame Potassium, Sucralose, Caffeine, Inositol, Lysine, Choline Bitartrate, Vitamin B3, Vitamin B5, Tartrazine, Ponceau 4R, Vitamin B6, Vitamin B12',NULL,'Red Bull Plus Zero Sugar Energy Drink','Sodium Benzoate',1,0,250,275,'Sugar Free Energy Drink',0,0,0,NULL),
('BE21','Natural Plant-Based Caffeine, Green Tea Extract, B-Vitamins','O\'cean',NULL,NULL,NULL,'Beverages',0,NULL,'24','Carbonated Water, Glucose, Natural Plant-Based Caffeine from Green Tea Extract, Acidity Regulators, Flavouring Substances, B-Vitamins',NULL,'Natural Plant Based Energy Drink',NULL,NULL,NULL,250,NULL,'Energy Drink',NULL,NULL,NULL,NULL),
('BE22','Electrolytes, Vitamins B3, B5, B7, Acidity Regulators, Flavouring Substances','O\'cean',NULL,NULL,NULL,'Beverages',0,NULL,'24','Water, Mango, Passion Fruit, Fruit Juice, Sugar, Electrolytes, Acidity Regulators, Natural Flavouring Substances, Vitamins B3, B5, B7',NULL,'Mango & Passion Fruit Water',NULL,NULL,0,250,NULL,'Fruit Drink',NULL,0,0,NULL),
('BE23','INS 330, INS 331(iii), INS 414, INS 445, INS 122, INS 102, INS 110, Taurine, Caffeine, Inositol, Vitamins B3, B6, B12','NON STOP',NULL,111,27,'Beverages',0,0,'24','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331(iii)), Natural and Nature Identical Flavouring Substances (Pineapple, Cooling, Guava), Taurine, Caffeine, Inositol, Vitamins B3, B6, B12, Dextrose Monohydrate, Emulsifiers (INS 414, INS 445), Preservatives (INS 202, INS 211), Permitted Synthetic Food Colours (INS 122, INS 102, INS 110)',NULL,'NON STOP Boost Energy Drink','INS 202, INS 211',0,0,250,86.75,'Energy Drink',27,0,0,NULL),
('BE24','Electrolytes, Acidity Regulators, Flavouring Substances, Vitamins','Glucon-D',NULL,NULL,NULL,'Beverages',0,NULL,'24','Water, Glucose, Electrolytes, Acidity Regulators, Green Apple Flavour, Vitamins',NULL,'Glucon-D Recharge Green Apple',NULL,NULL,0,500,NULL,'Hydration Drink',NULL,0,0,NULL),
('BE25','Electrolytes, Vitamin C, Vitamin B12, Acidity Regulators, Sweetener','Fast&Up',NULL,NULL,0.64,'Beverages',0,0,'24','Water, Electrolytes (Sodium, Potassium, Magnesium, Calcium, Chloride), Fructose, Acidity Regulators, Lemon Flavour, Vitamin C, Vitamin B12, Sweetener',NULL,'Reload Lemon Blast Energy Drink',NULL,0,0,250,NULL,'Electrolyte Hydration Drink',0.64,0,0,NULL),
('BE26','Taurine, Caffeine, B-Vitamins, Sweeteners','XTCY',NULL,0,0,'Beverages',0,0,'24','Carbonated Water, Acidity Regulators, Natural and Nature Identical Flavouring Substances, Taurine, Caffeine, B-Vitamins, Sweeteners',NULL,'XTCY Mango Bango Energy Drink',NULL,0,0,NULL,NULL,'Sugar Free Energy Drink',0,0,0,NULL),
('BE27','INS 968, INS 955, INS 330, INS 331(iii), INS 129, INS 122, INS 133','Paper Boat',NULL,0,0,'Beverages',0,7.5,'24','Carbonated Water, Erythritol, Sweeteners (INS 968, INS 955), Acidity Regulators (INS 330, INS 331(iii)), Natural and Nature Identical Flavouring Substances, Preservative (INS 211), Iodised Salt, Food Colours',NULL,'Zero Prebiotic Soda Cranberry Lime','INS 211',0,0,300,78,'Prebiotic Soda',0,0,0,NULL),
('BE28','INS 968, INS 955, INS 330, INS 331(iii), Flavouring Substances','Paper Boat',NULL,0,0,'Beverages',0,7.5,'24','Carbonated Water, Erythritol, Sweeteners (INS 968, INS 955), Acidity Regulators (INS 330, INS 331(iii)), Natural and Nature Identical Flavouring Substances, Preservative (INS 211)',NULL,'Zero Prebiotic Soda Mint Mojito','INS 211',0,0,300,93,'Prebiotic Soda',0,0,0,NULL),
('BE29','INS 330, INS 331(iii), Taurine, Caffeine, Inositol, Vitamins B3, B6, B12, INS 133','NON STOP',NULL,115,28,'Beverages',0,0,'24','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331(iii)), Taurine, Caffeine, Inositol, Vitamins B3, B6, B12, Dextrose Monohydrate, Natural and Nature Identical Flavouring Substances, Preservatives (INS 202, INS 211), Food Colour INS 133',NULL,'NON STOP Jungle Energy Drink','INS 202, INS 211',1.1,0,250,86.8,'Energy Drink',28,0.8,0,NULL),
('BE3','Sucralose, Xanthan Gum, Sodium Alginate, INS/food additives from acidity regulators and stabilisers','Monster Energy',0,245,62,'Beverages',0,0,'24','Carbonated Water, Fruit Juices from Concentrate (15%) (Guava, Mango, White Grape, Apple, Pineapple, Apricot, Orange, Peach, Lemon, Passion Fruit), Sucrose, Glucose Syrup, Citric Acid, Taurine (0.4%), Potassium Citrate, Sodium Citrate, Flavourings, Potassium Sorbate, Sodium Benzoate, Caffeine (0.03%), Vitamins (B2, B3, B6, B12), Xanthan Gum, Sodium Alginate, Sucralose, L-Carnitine L-Tartrate (0.004%), Inositol (0.002%), Carotenes, Vegetable Oils, Modified Starch, Sodium Chloride, Maltodextrin',0,'Monster Juice Mango Loco','Potassium Sorbate, Sodium Benzoate',0,0,500,72,'Energy Drink',58,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BE30','Natural Caffeine from Green Tea, Taurine, Vitamins B3, B6, B12, Sweeteners, Acidity Regulators','Red Bull',NULL,0,0,'Beverages',0,0,'24','Carbonated Water, Acidity Regulators, Natural Caffeine from Green Tea, Taurine, Flavouring Substances, Vitamins B3, B6, B12, Sweeteners',NULL,'Red Bull Soda Blueberry Blackcurrant',NULL,0,0,250,NULL,'Sugar Free Energy Drink',0,0,0,NULL),
('BE4','Erythritol, Sucralose, Acesulfame K, Citric Acid, Sodium Citrates, L-Carnitine L-Tartrate, Inositol','Monster Energy',0,14,7,'Beverages',0,0,'9','Carbonated Water, Citric Acid, Erythritol, Taurine (0.4%), Sodium Citrates, Flavourings, Panax Ginseng Root Extract (0.08%), Sorbic Acid, Benzoic Acid, Sucralose, Acesulfame K, Caffeine (0.03%), L-Carnitine L-Tartrate (0.015%), Vitamins B3, B5, B6, B12, Purple Sweet Potato Concentrate, Inositol',0,'Monster Energy Ultra Rosa','Sorbic Acid, Benzoic Acid',0,0,500,400,'Energy Drink',0,0,0,'Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B12'),
('BE5','Sodium Citrate, Sucralose, Gum Arabic, Ester Gum, Red 40, Blue 1, Maltodextrin','Monster Energy',0,210,53,'Beverages',0,0,'24','Carbonated Water, Sugar, Glucose, Orange Juice Concentrate, Apple Juice Concentrate, Taurine, Citric Acid, Raspberry Juice Concentrate, Guava Puree, Cherry Juice Concentrate, Sodium Citrate, Potassium Sorbate, Caffeine, Maltodextrin, Sodium Benzoate, Natural Flavors, Niacinamide (Vitamin B3), Sucralose, Pineapple Juice Concentrate, Passionfruit Juice Concentrate, Gum Arabic, Red 40, Salt, Ester Gum, Inositol, L-Carnitine L-Tartrate, Pyridoxine Hydrochloride (Vitamin B6), Riboflavin (Vitamin B2), Blue 1, Cyanocobalamin (Vitamin B12)',0,'Monster Pacific Punch','Potassium Sorbate, Sodium Benzoate',0,0,500,80,'Energy Drink',51,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BE6','Taurine, Sodium Citrate, Maltodextrin, Sucralose, L-Carnitine L-Tartrate, Inositol, Flavourings','Monster Energy',0,235,57,'Beverages',0,0,'24','Carbonated & Nitrogenated Water, Sugar, Glucose Syrup, Citric Acid, Taurine (0.4%), Sodium Citrate, Panax Ginseng Root Extract, Natural Flavours, Maltodextrin, Potassium Sorbate, Caffeine (0.03%), Sodium Benzoate, Vitamins B3, B6, B2, B12, L-Carnitine L-Tartrate, Sucralose, Inositol, Colour',0,'Monster Energy Nitro Cosmic Peach','Potassium Sorbate, Sodium Benzoate',0,0,500,240,'Energy Drink',53,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BE7','Citric Acid, Sodium Citrate, Malic Acid, Potassium Citrate, Sucralose, Glycerol Esters of Wood Rosins','Monster Energy',0,212,55,'Beverages',0,0,'24','Carbonated Water, Sucrose, Glucose, Lemon Juice From Concentrate, Citric Acid, Sodium Citrate, Malic Acid, Potassium Citrate, Taurine (0.4%), Flavourings, Panax Ginseng Extract, Potassium Sorbate, Caffeine, Vitamins B3, B6, B2, B12, Glycerol Esters of Wood Rosins, Salt, Sucralose, Guarana Seed Extract, Inositol',0,'Monster Juiced Aussie Lemonade Style','Potassium Sorbate',0,0,500,165,'Energy Drink',50,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BE8','Sucralose, Acesulfame K, Maltodextrin, Citric Acid, Sodium Citrates, L-Carnitine, Inositol, Colours E102/E110','Monster Energy',0,13,3.7,'Beverages',0,0,'24','Carbonated Water, Citric Acid, Taurine (0.4%), Sodium Citrates, Maltodextrin, Panax Ginseng Root Extract, Flavourings, Potassium Sorbate, Sodium Benzoate, Sucralose, Acesulfame K, Caffeine (0.03%), Vegetable Oils (Coconut, Rapeseed), L-Carnitine L-Tartrate, Modified Starch, Vitamins B3, B5, B6, B12, Sodium Chloride, Guarana Seed Extract, Inositol, Colours E102, E110',0,'Monster Energy Ultra Peachy Keen','Potassium Sorbate, Sodium Benzoate',0,0,500,316,'Energy Drink',0,0,0,'Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B12'),
('BE9','Sucralose, Acesulfame K, Maltodextrin, Citric Acid, Sodium Citrates, L-Carnitine, Inositol, Colours E102, E129','Monster Energy',0,14,3.9,'Beverages',0,0,'24','Carbonated Water, Citric Acid, Taurine (0.4%), Sodium Citrates, Maltodextrin, Flavourings, Potassium Sorbate, Sodium Benzoate, Sucralose, Acesulfame K, Caffeine (0.03%), Vegetable Oils (Coconut, Rapeseed), Modified Starch, Vitamins B3, B6, B2, B12, L-Carnitine L-Tartrate, Sodium Chloride, Inositol, Colours E102, E129',0,'Monster Energy Lewis Hamilton Zero Sugar','Potassium Sorbate, Sodium Benzoate',0,0,500,320,'Energy Drink',0,0,0,'Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B12'),
('BM1','INS 415, INS 412, INS 407, INS 452(i), INS 436, Added Flavour','Cavin\'s',196,223.4,31.4,'Beverages',26,0,'9','Standardized Milk (89%), Sugar, Stabilizers (INS 415, INS 412, INS 407), Sequestering Agent, Iodized Salt, Emulsifier (INS 436), Vitamin and Mineral Premix (Zinc, Vitamin A, Vitamin D), Added Flavour',0,'Cavin\'s Vanilla Milkshake','No added preservatives',6,5.4,200,160,'Milkshake',31,8.2,0.2,'Vitamin A, Vitamin D, Zinc'),
('BM10','Acidity Regulator (INS 339(ii)), Stabilizers (INS 418, INS 407), Added Vitamins and Minerals','Boost',60,70,11,'Beverages',5.5,0.1,'9 Months','Toned Milk, Water, Sugar, Cereal Product, Milk Solids, Minerals, Acidity Regulator (INS 339(ii)), Stabilizers (INS 418, INS 407), Vitamins, Badam Flavouring',0,'Boost Badam Flavour Milkshake','Not Specified',2.7,1.6,180,70,'Milkshake',10,1.7,0,'Vitamin A, Vitamin B1, Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B9, Vitamin B12, Vitamin D2'),
('BM11','Acidity Regulator (INS 339(ii)), Stabilizers (INS 418, INS 407), Added Vitamins and Minerals','Boost',60,70,11,'Beverages',5.5,0.1,'9 Months','Toned Milk (60%), Water, Sugar, Cereal Product (3%), Milk Solids, Minerals, Acidity Regulator (INS 339(ii)), Stabilizers (INS 418, INS 407), Vitamins',0,'Boost Classic Milkshake','Not Specified',2.7,1.6,180,70,'Milkshake',10,1.7,0.01,'Vitamin A, Vitamin B1, Vitamin B2, Vitamin B3, Vitamin B6, Vitamin B9, Vitamin B12, Vitamin D2'),
('BM12','Sequestrant (INS 339(ii)), Stabilizer (INS 407), Synthetic Food Colours (INS 102, INS 110), Artificial Badam Flavouring','Cavin\'s',140,145,25,'Beverages',8.5,0,'9 Months','Double Toned Milk, Sugar, Almond Bits (0.4%), Artificial Badam Flavouring Substance, Sequestrant (INS 339(ii)), Stabilizer (INS 407), Synthetic Food Colours (INS 102, INS 110)',0,'Cavin\'s Badam Flavoured Milk','None Specified',5.4,1.7,170,98.6,'Flavoured Milk',24.8,2.5,0,'Not Specified'),
('BM13','Permitted Stabilizers, Emulsifiers and Flavouring Substances','Cavin\'s',140,135.3,17,'Beverages',0,0,'9 Months','Milk, Sugar, Almonds, Added Vitamins and Minerals, Permitted Stabilizers, Emulsifiers and Flavouring Substances',0,'Cavin\'s Badam Milkshake','None',4,0,170,0,'Milkshake',0,5.7,0,'Vitamin A, Vitamin D'),
('BM14','Stabilizers (INS 412, INS 415, INS 407), Sequestrant (INS 451(i)), Emulsifiers (INS 322(i), INS 471), Artificial and Natural Flavouring Substances','Cavin\'s',197,172.5,27,'Beverages',14,0,'9 Months','Double Toned Milk, Sugar, Cocoa Solids (1.5%), Belgian Chocolate (0.1%), Artificial Belgian Chocolate Flavouring Substances, Natural Flavouring Substance, Stabilizers (INS 412, INS 415, INS 407), Sequestrant (INS 451(i)), Emulsifiers (INS 322(i), INS 471)',0,'Cavin\'s Belgian Chocolate Milkshake','None Specified',5.8,2.9,170,161,'Milkshake',25.1,4.6,0.1,'Vitamin A, Vitamin D'),
('BM15','Zinc, Added Vitamins and Minerals, Permitted Stabilizers, Emulsifiers and Flavouring Substances','Cavin\'s',NULL,NULL,NULL,'Beverages',NULL,NULL,'9 Months','Milk, Sugar, Gulkand (Preserved Rose Petals), Added Vitamins and Minerals, Permitted Stabilizers, Emulsifiers and Flavouring Substances',NULL,'Cavin\'s Gulkand Milkshake','Not Specified',NULL,NULL,170,NULL,'Milkshake',NULL,NULL,NULL,'Vitamin A, Vitamin D'),
('BM16','Permitted Stabilizers, Emulsifiers and Flavouring Substances','Cavin\'s',NULL,NULL,NULL,'Beverages',NULL,NULL,'9 Months','Milk, Sugar, Cashew Nuts, Butterscotch Flavouring, Added Vitamins and Minerals, Permitted Stabilizers and Emulsifiers',NULL,'Cavin\'s Kaju Butterscotch Milkshake','Not Specified',NULL,NULL,180,NULL,'Milkshake',NULL,NULL,NULL,'Not Specified'),
('BM17','Stabilizer (INS 407), Emulsifier (INS 471), Sequestrants (INS 340(ii), INS 339(iii)), Artificial Rabdi and Condensed Milk Flavouring Substance, Zinc','Cavin\'s',190,240.1,30.6,'Beverages',17.7,0,'9 Months','Standardized Milk, Sugar, Stabilizer (INS 407), Emulsifier (INS 471), Sequestrants (INS 340(ii), INS 339(iii)), Artificial Rabdi and Condensed Milk Flavouring Substance, Iodized Salt',0,'Cavin\'s Rabdi Milkshake','None',5.7,4.9,170,106,'Milkshake',26.8,8.7,0.03,'Vitamin A, Vitamin D'),
('BM18','Emulsifiers (INS 460(i), INS 466), Mineral and Vitamin Premix (Zinc, Vitamin A, Vitamin D), Nature Identical Flavouring Substances','Cavin\'s',72,102,19,'Beverages',0,0,'9 Months','Standardized Milk Curd, Water, Sugar, Emulsifiers (INS 460(i), INS 466), Mineral and Vitamin Premix (Zinc, Vitamin A, Vitamin D), Nature Identical Flavouring Substances',0,'Cavin\'s Rose Lassi','None Specified',2,0,180,50,'Lassi',14,2,0,'Vitamin A, Vitamin D'),
('BM19','Emulsifiers, Stabilizers and Added Flavouring Substances','Cavin\'s',98,111.7,15.7,'Beverages',13,0,'9 Months','Standardized Milk Curd, Water, Sugar, Strawberry Solids, Emulsifiers, Stabilizers and Added Flavouring Substances',0,'Cavin\'s Strawberry Milkshake','Not Specified',3,2.7,180,80,'Milkshake',15.5,4.1,0.1,'Vitamin A, Vitamin D'),
('BM2','Synthetic Food Colour (INS 127), Artificial Rose Flavouring','Amul',0,90,12.5,'Beverages',9,0,'6 Months','Toned Milk, Sugar, Milk Solids, Synthetic Food Colour (INS 127), Artificial Flavouring Substances (Rose)',0,'Amul Kool Rose','Not Specified',3.1,1.9,100,43,'Flavoured Milk',12.5,3.1,0,'0.0'),
('BM20','Emulsifying Agent (INS 471), Stabilizing Agents (INS 407, INS 412, INS 415), Acidity Regulator (INS 339(ii)), Synthetic Food Colours (INS 102, INS 110), Nature Identical Flavouring Substances','Cream Bell',126,82,12,'Beverages',6,0,'6 Months','Double Toned Milk (86%), Water, Sugar, Milk Solids, Permitted Emulsifying Agent (INS 471), Stabilizing Agents (INS 407, INS 412, INS 415), Acidity Regulator (INS 339(ii)), Saffron (0.0005%), Permitted Synthetic Food Colours (INS 102, INS 110), Nature Identical Flavouring Substances (Kesar Badam)',0,'Cream Bell Kesar Badam Milkshake','None Specified',3.3,1.2,180,50,'Milkshake',12.4,2,0,'Not Specified'),
('BM21','Emulsifiers (INS 460(i), INS 466, INS 471), Sequestrant (INS 339(ii)), Thickeners (INS 415, INS 407), Calcium Carbonate, Zinc Sulphate, Nature Identical Flavoring Substances','HERSHEY\'S',NULL,156,28.5,'Beverages',NULL,NULL,'9 Months','Water, Milk Solids (11%), Sugar, Emulsifiers (INS 460(i), INS 466, INS 471), Mineral (Calcium Carbonate), Nature Identical Flavoring Substances, Sequestrant (INS 339(ii)), Thickeners (INS 415, INS 407), Zinc Sulphate, Vitamin E Acetate, Vitamin A Acetate, Vitamin D2 (Ergocalciferol), Vitamin B1 (Thiamine Chloride Hydrochloride), Vitamin B2 (Riboflavin), Edible Common Salt, Almond Paste (0.002%)',NULL,'HERSHEY\'S Almond Flavored Milkshake','None Specified',3.6,NULL,180,NULL,'Milkshake',NULL,3,NULL,'Vitamin A, Vitamin B1, Vitamin B2, Vitamin D2, Vitamin E'),
('BM22','Acidity Regulators (INS 340, INS 452, INS 339(ii)), Stabilizer (INS 407), Sweetener (INS 955), Nature Identical Flavouring Substances','Epigamia',278,141,8,'Beverages',5,0,'6 Months','Ultrafiltered Skimmed Milk (79%), Water, Nature Identical Flavouring Substances (Cookies & Cream), Cocoa Powder, Acidity Regulators (INS 340, INS 452, INS 339(ii)), Edible Common Salt, Stabilizer (INS 407), Sweetener (INS 955)',0,'Epigamia Turbo 25g Protein Milkshake Cookies & Cream','None',25,0,250,284,'Protein Milkshake',7,1,0,'Not Specified'),
('BM23','Acidity Regulators [INS 340, INS 452, INS 339(ii)], Stabilizer (INS 407), Sweetener (INS 955), Nature Identical Flavouring Substances','Epigamia',412,136,8,'Beverages',0.6,0,'6 Months','Skimmed Milk (80%), Milk Solids, Water, Nature Identical Flavouring Substances (Vanilla and Caramel), Acidity Regulators [INS 340, INS 452, INS 339(ii)], Stabilizer (INS 407), Sweetener (INS 955), Edible Common Salt',0,'Epigamia Turbo 25g Protein Milkshake Vanilla Caramel','None',25,0,250,221,'Protein Milkshake',8,0.2,0,'Not Specified'),
('BM24','None Specified','Heritage',NULL,39.24,3.6,'Beverages',5.4,NULL,'6 Months','Water, Milk Solids (Toned Milk Curd), Iodized Salt, Spices and Condiments, Active Lactic Culture, Probiotic Bacterial Strains',NULL,'A-One Spiced Buttermilk','None Specified',2.16,1.17,180,369,'Buttermilk',NULL,1.8,0.072,'Not Specified'),
('BM3','INS 965(ii), INS 340(ii), INS 340(iii), INS 452(i), INS 339(iii), INS 460(i), INS 466','Horlicks',540,171,17,'Beverages',5,3.5,'6','Milk, Water, Sweetener (INS 965(ii)), Edible Fiber, Cocoa Powder, Cereal Product, Vitamins & Minerals, Nature Identical Flavouring Substances, Acidity Regulators (INS 340(ii), INS 340(iii), INS 452(i), INS 339(iii)), Stabilizers (INS 460(i), INS 466), Edible Iodised Salt',0,'Horlicks Protein Milkshake','No artificial preservatives',20,2.4,240,150,'Milkshake',8,3.6,0.01,'Vitamin B1, B2, B3, B6, B9, B12, D2'),
('BM4','INS 460(i), INS 466, INS 471, INS 339(ii), Calcium Carbonate, Zinc Sulphate','Hershey\'s',0,170,29,'Beverages',0,0,'9','Water, Milk Solids (8%), Sugar, Cocoa Solids (0.75%), Emulsifiers (INS 460(i), INS 466, INS 471), Calcium Carbonate, Flavours (Nature Identical Flavouring Substances), Sequestrant (INS 339(ii)), Iodised Salt, Zinc Sulphate, Vitamin E (Acetate), Vitamin A (Acetate), Vitamin D2 (Ergocalciferol), Vitamin B1 (Thiamine Chloride Hydrochloride), Vitamin B2 (Riboflavin)',0,'Hershey\'s Chocolate Milkshake','No added preservatives',4.4,2,180,93,'Milkshake',29,4.1,0.1,'Vitamin A, Vitamin D2, Vitamin E, Vitamin B1, Vitamin B2'),
('BM5','INS 407, INS 110, INS 102, Added Flavours','Amul',280,209,26,'Beverages',24,0,'6','Standardized Milk, Milk Solids, Sugar, Almond Pieces (0.5%), Permitted Stabilizer (E407), Permitted Synthetic Food Colours (E110, E102), Added Flavours (Artificial Flavouring Substances - Badam, Kesar & Elaichi)',0,'Amul Badam Shakers','None listed',6,5.6,200,84,'Milkshake',26,9,0,'0.0'),
('BM7','None','Amul',110,58.2,4.8,'Dairy Products',10,0,'6 Months','Toned Milk',0,'Amul Taaza UHT Milk','None',3,2,200,37,'Toned Milk',4.8,3,0,'Vitamin A, Vitamin D'),
('BM8','Permitted Stabilizer (INS 460(i))','Amul',75,29.3,2.3,'Beverages',4,0,'9 Months','Milk Solids, Water, Iodized Salt, Spices and Condiments, Permitted Stabilizer (INS 460(i))',0,'Amul Masti Spiced Buttermilk','None Specified',1.7,1,200,27.5,'Buttermilk',0,1.5,0.1,'Not Specified'),
('BM9','Sweetener (INS 965, INS 960), Stabilizers (INS 440, INS 418), Acidity Regulator (INS 330), Colours (INS 133, INS 122), Artificial Flavouring Substances','Amul',0,138,19,'Beverages',4,0,'6 Months','Milk Solids, Water, Sweetener (INS 965, INS 960), Blueberry Fruit Preparation (3.5%) [Blueberry Fruit, Water, Nature Identical Flavouring Substances, Stabilizer (INS 440), Acidity Regulator (INS 330), Colours (INS 133, INS 122)], Acidity Regulator (INS 330), Stabilizers (INS 440, INS 418), Artificial Flavouring Substances (Blueberry)',0,'Amul High Protein Blueberry Shake','None Specified',20,1,200,40,'Protein Milkshake',3.3,1.5,0,'Not Specified'),
('BS1','INS 338, INS 150d, Caffeine, Natural Flavouring Substances','Coca-Cola',0,88,21.8,'Beverages',0,0,'3','Carbonated Water, Sugar, Acidity Regulator (INS 338), Caffeine (8.7 mg/100 g), Colour (INS 150d), Flavours (Natural Flavouring Substances)',0,'Coca-Cola Original Taste','None listed',0,0,200,17,'Soft Drink',21.2,0,0,'0.0'),
('BS10','INS 330, INS 331, INS 1450, INS 445, INS 110, Natural Flavouring Substances','Mirinda',0,56,14,'Beverages',0,0,'4','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331), Stabilizers (INS 1450, INS 445), Preservative (INS 211), Permitted Synthetic Colour (INS 110), Natural Flavouring Substances',0,'Mirinda Orange Flavoured Soft Drink','INS 211 (Sodium Benzoate)',0,0,100,10,'Soft Drink',14,0,0,''),
('BS11','INS 330, INS 331, INS 445, INS 102, Natural Flavouring Substances','Mountain Dew',0,98,24.6,'Beverages',0,0,'4','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331), Added Flavour (Natural Flavouring Substances), Preservative (INS 211), Caffeine, Stabilizer (INS 445), Permitted Synthetic Food Colour (INS 102)',0,'Mountain Dew Citrus Soft Drink','INS 211 (Sodium Benzoate)',0,0,200,16,'Soft Drink',24.6,0,0,''),
('BS12','INS 290, INS 296, INS 331(iii), INS 330, INS 440, INS 150d, INS 300, Nature-Identical Apple Flavouring Substance','Appy Fizz',0,51.8,12.95,'Beverages',0,0,'4','Water, Sugar, Carbonating Agent (INS 290), Acidity Regulators (INS 296, INS 331(iii), INS 330), Stabilizer (INS 440), Natural Colour (INS 150d), Preservative (INS 211), Antioxidant (INS 300), Nature-Identical Flavouring Substance (Apple)',0,'Appy Fizz Apple Flavoured Sparkling Drink','INS 211 (Sodium Benzoate)',0,0,100,21.2,'Soft Drink',12.9,0,0,''),
('BS2','INS 338, INS 331, INS 955, INS 950, INS 150d, Caffeine, Natural Cola-type Flavours','Coca-Cola',0,0,0,'Beverages',0,0,'4','Carbonated Water, Acidity Regulators (INS 338, INS 331), Sweeteners (INS 955, INS 950), Preservative (INS 211), Caffeine, Colour (INS 150d), Natural Cola-type Flavours',0,'Coca-Cola Zero Sugar','INS 211 (Sodium Benzoate)',0,0,200,15,'Soft Drink',0,0,0,'0.0'),
('BS3','INS 338, INS 331(iii), INS 951, INS 950, INS 150d','Coca-Cola',0,0,0,'Beverages',0,0,'6','Carbonated Water, Acidity Regulators (338, 331(iii)), Sweeteners (951, 950), Preservative (211), Caffeine (10 mg/100g), Colour (150d), Flavours (Natural Flavouring Substances)',0,'Diet Coke','INS 211',0,0,200,8.3,'Soft Drink',0,0,0,'0.0'),
('BS4','INS 338, INS 150d, Added Cola Flavouring Substances, Caffeine','Coca-Cola',0,84,21.2,'Beverages',0,0,'3','Carbonated Water, Sugar, Acidity Regulator (338), Caffeine, Permitted Natural Colour (150d), Added Flavours (Natural, Nature-Identical and Artificial Flavouring Substances - Cola Flavour)',0,'Thums Up','None listed',0,0,200,1.62,'Soft Drink',20.8,0,0,'0.0'),
('BS5','INS 330, INS 331(iii)','Coca-Cola',0,98,24.4,'Beverages',0,0,'3','Carbonated Water, Sugar, Acidity Regulators (330, 331(iii)), Preservative (211), Flavours (Natural Flavouring Substances)',0,'Sprite','INS 211',0,0,200,20.2,'Soft Drink',23.4,0,0,'0.0'),
('BS6','INS 330, INS 331(iii), INS 414, INS 471, Lemon Flavouring Substances','Limca',0,44,11.1,'Beverages',0,0,'6','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331(iii)), Stabilizers (INS 414, INS 471), Preservative (INS 211), Flavours (Natural, Nature-Identical & Artificial Lemon Flavouring Substances)',0,'Limca Lime-Lemon Soft Drink','INS 211 (Sodium Benzoate)',0,0,100,5.6,'Soft Drink',10.7,0,0,''),
('BS7','INS 330, INS 414, INS 445, INS 110, Natural and Nature-Identical Flavouring Substances','Fanta',0,56,14,'Beverages',0,0,'6','Carbonated Water, Sugar, Acidity Regulator (INS 330), Stabilizers (INS 414, INS 445), Preservative (INS 211), Colour (INS 110), Natural and Nature-Identical Flavouring Substances',0,'Fanta Orange Soft Drink','INS 211 (Sodium Benzoate)',0,0,100,22.3,'Soft Drink',13.7,0,0,''),
('BS8','INS 330 (Citric Acid), INS 331, INS 296, Lemon-Lime Flavouring Substances','7UP',0,46,11.4,'Beverages',0,0,'','Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331, INS 296), Preservative (INS 211), Lemon-Lime Flavouring Substances',0,'7UP Lemon-Lime Soft Drink','INS 211 (Sodium Benzoate)',0,0,100,27,' Soft Drink',11.4,0,0,''),
('BS9','INS 331(iii), INS 296, INS 330, INS 445(iii), Natural Flavouring Substances','7UP Nimbooz',0,84,21.2,'Beverages',0,0,'4','Water, Sugar, Concentrated Lemon Juice (0.7%), Acidity Regulators (INS 331(iii), INS 296, INS 330), Natural Flavouring Substances, Iodised Salt, Stabilizer (INS 445(iii)), Preservative (INS 202)',0,'7UP Nimbooz with Lemon Juice','INS 202 (Potassium Sorbate)',0,0,200,65,'Soft Drink',21.2,0,0,''),
('SB1','INS 500(ii), INS 503(ii), INS 322, Nature Identical Flavouring Substances','Cadbury Oreo',0,482,71.2,'Solid items',0,0,'6','Refined Wheat Flour, Sugar, Edible Vegetable Fat, Palmolein Oil, Cocoa Solids (3%), Invert Syrup, Leavening Agents (INS 500(ii), INS 503(ii)), Iodised Salt, Emulsifier (INS 322), Nature Identical Flavouring Substances',0,'Cadbury Oreo Original Chocolatey Sandwich Biscuits','None specifically listed',5.3,9.8,100,420,'Biscuits',36.5,19.7,0.1,'0.0'),
('SB2','INS 503(ii), INS 500(ii), INS 322(i), INS 471, INS 330, INS 334, INS 627, INS 631, INS 551, INS 223, INS 1450, INS 110','Britannia',0,485,71.3,'Solid items',0,0,'6','Refined Wheat Flour, Refined Palmolein & Palm Oil, Sugar, Dehydrated Potato Flakes (11.3%), Iodised Salt, Spices & Condiments, Raising Agents (INS 503(ii), INS 500(ii)), Liquid Glucose, Milk Solids, Invert Sugar Syrup, Rice Flour, Vital Gluten, Natural & Nature Identical Flavouring Substances, Emulsifiers (INS 322(i), INS 471), Maltodextrin, Dry Mango Powder, Acidity Regulators (INS 330, INS 334), Flavour Enhancers (INS 627, INS 631), Anticaking Agent (INS 551), Dough Conditioner (INS 223), Stabilizer (INS 1450), Colour (INS 110)',0,'Britannia 50-50 Potazos Masti Masala','None specifically listed',8,9,100,1188,'Biscuits',17.1,18.7,0,'0.0'),
('SB3','Not completely specified on the available product listing','Britannia',0,486,69.8,'Solid items',0,0,'6','Wheat Flour, Milk Ingredients, Vegetable Fat/Oil, Sugar, Cheese/Dairy Ingredients, Salt, Raising Agents, Emulsifiers, Flavouring Substances and permitted food additives',0,'Britannia 50-50 Cheeze Dipped Crunchy Layered Sandwich','Not specifically listed',7.9,12.9,100,445,' Biscuit',17.4,19.5,0,'0.0'),
('SB4','INS 500(ii), INS 503(ii), INS 450(i), INS 322(i), INS 471, INS 472e, Flavouring Substances','Britannia',0,506,68.2,'Solid items',4.2,0,'6','Refined Wheat Flour (Maida), Refined Palm Oil, Sugar, Spices (Cumin 2.4% and Ajwain), Raising Agents (INS 500(ii), INS 503(ii)), Invert Sugar Syrup, Butter (1.4%), Iodised Salt, Milk Solids, Emulsifier (INS 322(i)), Mono- and Diglycerides (INS 471), Emulsifier (INS 472e), Natural and Nature-Identical Flavouring Substances',0,'Britannia Good Day Crafted Butter Jeera Cookies','None specifically listed',6.4,11.5,100,592,'Biscuit',20.8,23.1,0,'0.0'),
('SB5','INS 503(ii), INS 500(ii), INS 322, INS 471, INS 472e, Flavouring Substances','Britannia',0,512,67,'Solid items',2.5,0,'6','Wheat Flour, Vegetable Fat (Palm), Sugar, Cashew Bits, Invert Sugar, Whole Milk Powder, Butter, Raising Agents (INS 503(ii), INS 500(ii)), Salt, Soya Lecithin (INS 322), Mono & Diglycerides of Fatty Acids (INS 471), Diacetyl Tartaric Acid Esters of Mono & Diglycerides (INS 472e), Butter, Milk, Nut & Vanilla Flavours',0,'Britannia Good Day Cashew Cookies','None specifically listed',7,11,100,0,'Biscuit',22,24,0,'0.0'),
('SC1','INS 319','Let\'s Try',18,270,29,'Solid items',0,2.5,'6','Potatoes, Groundnut Oil, Salt',1.1,'Potato Wafers','TBHQ',3,5,50,320,'Chips',1,16,0.1,'0.5'),
('SC2','INS 322, INS 476, Added Flavours','Amul',0,222.8,22.9,'Solids items',0,0,'12','Sugar, Cocoa Solids, Cocoa Butter, Permitted Emulsifiers (E322, E476), Added Flavours (Artificial Flavouring Substances - Cocoa and Vanilla)',0,'Amul Dark Chocolate','None specifically listed',2.4,8.2,40,0,'Chocolate',17.2,13.5,0,'0.0'),
('SC3','Not specified','Amul',0,0,0,'Solid items',0,0,'12','Milk Chocolate, Roasted Peanuts',0,'Amul Crunchy Peanut Milk Chocolate','None specifically identified',0,0,150,0,'Chocolate',0,0,0,'0.0'),
('SC4','INS 322, INS 476, Added Flavours','Amul',0,557,57.3,'Solid items',0,0,'12','Sugar, Cocoa Solids, Cocoa Butter, Permitted Emulsifiers (E322, E476), Added Flavours (Artificial Flavouring Substances - Cocoa and Vanilla)',0,'Amul Dark Chocolate 55%','None specifically listed',6,20.4,100,0,'Chocolate',43,33.7,0,'0.0'),
('SC5','INS 322, INS 476, Added Flavours','Amul',0,557,57.3,'Solid items',0,0,'12','Sugar, Cocoa Butter, Cocoa Solids, Permitted Emulsifiers (E322, E476), Added Flavours (Artificial Flavouring Substances - Cocoa and Vanilla)',0,'Amul India Twilight Tryst 55% Dark Chocolate','None specifically listed',6,20.4,100,0,'Chocolate',43,33.7,0,'0.0');
/*!40000 ALTER TABLE `food` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `food_properties`
--

DROP TABLE IF EXISTS `food_properties`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `food_properties` (
  `rule_id` int(11) NOT NULL,
  `brand_name` varchar(255) DEFAULT NULL,
  `calcium_mg` varchar(255) DEFAULT NULL,
  `calories_kcal` varchar(255) DEFAULT NULL,
  `carbohydrates_g` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `cholesterol_mg` varchar(255) DEFAULT NULL,
  `dietary_fiber_g` varchar(255) DEFAULT NULL,
  `ingredients` varchar(255) DEFAULT NULL,
  `iron_mg` varchar(255) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `proteins_g` varchar(255) DEFAULT NULL,
  `saturated_fat_g` varchar(255) DEFAULT NULL,
  `serving_size_g` varchar(255) DEFAULT NULL,
  `sodium_mg` varchar(255) DEFAULT NULL,
  `sub_category` varchar(255) DEFAULT NULL,
  `sugar_g` varchar(255) DEFAULT NULL,
  `total_fat_g` varchar(255) DEFAULT NULL,
  `trans_fat_g` varchar(255) DEFAULT NULL,
  `vitamin` varchar(255) DEFAULT NULL,
  `additives` varchar(255) DEFAULT NULL,
  `expire_data` varchar(255) DEFAULT NULL,
  `mfg_data` varchar(255) DEFAULT NULL,
  `preservatives` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`rule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `food_properties`
--

LOCK TABLES `food_properties` WRITE;
/*!40000 ALTER TABLE `food_properties` DISABLE KEYS */;
/*!40000 ALTER TABLE `food_properties` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping routines for database 'sih_db'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

-- Dump completed on 2026-09-08 11:41:44
